### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by apanzerj** [agilecrm/php-api#1]
It would be nice if you could attribute me (well, Zendesk, I developed it) for this as it came from over here https://gist.github.com/apanzerj/2920899 :-D 

It would just be nice. 

Thanks

Adam Panzer
@apanzerj
Zendesk Developer

**Comment by karthikagile** [comment]
@apanzerj  thank you

**Comment by apanzerj** [comment]
@karthikagile no problem. Can you let me know when the readme is updated?

**Comment by apanzerj** [comment]
Hi,

Still wondering if you are planning to give proper attribution for this...

**Comment by karthikagile** [comment]
Hi @apanzerj , 

Added attribution to updated https://github.com/agilecrm/php-api/blob/master/README.md thank you once again for allowing us to reuse the curlwrap.php code
