### ISSUE TITLE
Update Star Value doesn't work

### ISSUE THREAD

**Issue by mcpacific** [agilecrm/php-api#11]
I used the $contact_json in your example, substituting an actual Contact ID, and I get no error but the star value never updates. Looking at the REST API examples I've determined there is an error in your example. It should be "curl_wrap("contacts/edit/add-star", $contact_json, "PUT", "application/json");

**Comment by graut** [comment]
Hi @mcpacific,

Thank you for pointing out error. We modified documentation with correct api call.

Thanks

**Comment by TinyScreenLabs** [comment]
You should update he docs on the readme as well.

2.5 Update star value of a company

**Comment by graut** [comment]
Hi @TinyScreenLabs 

Thank you for pointing out error. We modified documentation with correct api call.

Thanks
