### ISSUE TITLE
create contact with company

### ISSUE THREAD

**Issue by bjornTeulinghx** [agilecrm/php-api#12]
Is it possible to give the company name to the json when you are creating a contact?

**Comment by graut** [comment]
Hi @bjornTeulinghx 

You can follow below steps : 

**Step 1 :** 

Search company in Agile CRM by company name if all ready present or not?

$lisOfcompanies = curl_wrap("search?q=Google&page_size=10&type='COMPANY'", null, "GET", "application/json");

// Get one company from list of companies

$single_comapny_by_name_google = $lisOfcompanies[0]  // Do your iteration and length checking

// Get company ID of Google

$contact_company_id = $single_comapny_by_name_google->id;  // ID should be Long type and not exponential type

**Reference :** https://github.com/agilecrm/php-api#27-search-contactscompanies

**Step 2 :** 

Create contact with company name


$contact_json = array(
  "lead_score"=>"80",
  "star_value"=>"5",
  "contact_company_id"=>$contact_company_id,  // Use company ID of google company
  "properties"=>array(
    array(
      "name"=>"first_name",
      "value"=>"Ronaldo",
      "type"=>"SYSTEM"
    ),
    array(
      "name"=>"last_name",
      "value"=>"de Lima",
      "type"=>"SYSTEM"
    ),
    array(
      "name"=>"email",
      "value"=>"abc@test.com",
      "type"=>"SYSTEM"
    ),
    array(
      "name"=>"company",
      "value"=>"Google",
      "type"=>"SYSTEM"
    )

  )
);

$contact_json = json_encode($contact_json);
curl_wrap("contacts", $contact_json, "POST", "application/json");

**Reference :** https://github.com/agilecrm/php-api#11-to-create-a-contact


**Note :** 
If you are not setting below field 
**"contact_company_id"=>$contact_company_id**

then new company will be create with Google name, So step one is recommended to get company ID and checking duplicate.
