### ISSUE TITLE
Update contact if already exists

### ISSUE THREAD

**Issue by cscheltinga** [agilecrm/php-api#13]
When trying to add a contact using:
`curl_wrap("contacts", $contact_json, "POST", "application/json")` it works great. But if the contact already exists; nothing happens. 

You'd like to be able to update contact if it exists, or else create new contact.

**Comment by graut** [comment]
Hi @cscheltinga ,

Above API only for creating contact. If you have same email present all ready then you will get duplicate error. 

You can follow below step. 

1. Get contact by  ID or  email

reference  - https://github.com/agilecrm/php-api#12-to-fetch-contact-data

2. If no contact found create new contact

reference - https://github.com/agilecrm/php-api#11-to-create-a-contact

3. If contact found update it

reference - https://github.com/agilecrm/php-api#14-update-properties-of-a-contact-partial-update

Note : Currently we don't have API which will create and update contact at same time.

**Comment by cscheltinga** [comment]
That's what I just created, thnx! 
Would be nice to have on call to create/update at once though :-)
