### ISSUE TITLE
Create/update opportunity with tags?

### ISSUE THREAD

**Issue by kennethkeyzw** [agilecrm/php-api#16]
How can I also include tags when creating a deal?

**Comment by rammohan-agile** [comment]
hi @kennethkeyzw   yes we can create Tags while creating a Deal please follow below code 

$opportunity_json = array(
  "name"=>"pppp deal",
  "description"=>"this is a test deal",
  "expected_value"=>1000,
  "milestone"=>"New", 
    "custom_data"=>array(
    array(
      "name"=>"dataone",
      "value"=>"xyz"
    ),
    array(
      "name"=>"datatwo",
      "value"=>"abc"
    )
  ),
    "tagsWithTime"=>array(
      array(
        "tag"=>"tagone"
      ),
      array(
        "tag"=>"tagtwo"
      )
    ),
  "probability"=>50,
  "close_date"=>0,
  "contact_ids"=>array("5641841626054656", "5756422495141888")
);

it will create a DEAL with tags.
Hope This will Help You, Please contact Agile CRM if you need any further help.

Thanks,
Agile CRM Support Team.
