### ISSUE TITLE
Beeing able to create, update, list, delete and assign Deal's Sources and Deal's Tags

### ISSUE THREAD

**Issue by marquilio7** [agilecrm/php-api#17]
Hello agilecrm team,

I've using you api and had great results but i've encounter some lacks that would be great to fulfill:

- Beeing able to create, update, list and delete Deal Sources and assign them to Deals.
- Beeing able to add, update or remove Deal's tags (just like with contacts).

Thanks in advance!

**Comment by rammohan-agile** [comment]
hi @mrestom  yes we can create Tags while creating a Deal please follow below code

$opportunity_json = array(
"name"=>"pppp deal",
"description"=>"this is a test deal",
"expected_value"=>1000,
"milestone"=>"New",
"custom_data"=>array(
array(
"name"=>"dataone",
"value"=>"xyz"
),
array(
"name"=>"datatwo",
"value"=>"abc"
)
),
"tagsWithTime"=>array(
array(
"tag"=>"tagone"
),
array(
"tag"=>"tagtwo"
)
),
"probability"=>50,
"close_date"=>0,
"contact_ids"=>array("5641841626054656", "5756422495141888")
);

it will create a DEAL with tags.
Hope This will Help You, Please contact Agile CRM if you need any further help.

Thanks,
Agile CRM Support Team.
