### ISSUE TITLE
Beeing able to get Deal's Tasks

### ISSUE THREAD

**Issue by marquilio7** [agilecrm/php-api#18]
Hello agilecrm team,

It would be great if you could implemente a way to get a Deal's Tasks.

Thanks in advance!

**Comment by rammohan-agile** [comment]
Hi @mrestom 
In Postman you can try like Below
select Basic Auth give user name and Password

https://{domain}.agilecrm.com/dev/api/opportunity/{Deal_id}/tasks

Request type : GET

please select below HEADERS
Content-Type     : application/json,
Accept		  : application/json,

for more details : https://github.com/agilecrm/rest-api#31-listing-deals
Hope This Help You, Please contact Agile CRM if need any further help.

Thanks.
