### ISSUE TITLE
no response

### ISSUE THREAD

**Issue by gaisho** [agilecrm/php-api#4]
I'm not getting any response.  I'm using the wrapper.  All I did was replace the DEFINE(...,..)... with my own details, and ran the search example but I don't get any response

I'm calling the api from localhost:  Could this be the problem?

**Comment by graut** [comment]
Calling from localhost is just fine.

Is it working with DEFINE(....)?

Please check this below code:
https://github.com/agilecrm/php-api/blob/master/PHP_API_v2.0.0.php

You can directly test above code with your domain,email and api key.

Note: If you are getting empty response then might be your php settings not support CURL. So please verify whether your php settings support curl by googling.

Advice:-
1.Please follow the step describe in the below url: (Subject :- Use the following steps to install curl: by curiousBoy)

http://stackoverflow.com/questions/181082/how-do-i-install-curl-on-windows
1. Once this is done please find the step describe in the below url:

http://www.tonyspencer.com/2003/10/22/curl-with-php-and-apache-on-windows/

Note:
a> if you have all ready php with xampp or any server installed, you can start with step number 3 of above url.
b> Check your php and copy corresponding .dll file which is mentioned at step number3.
c> don't for get to include : -curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
1. For our sample to get contact we are sharing you php file at below url.

http://justpaste.it/lzqm
You can directly paste and test with your domain ,api,user.

**Comment by rammohan-agile** [comment]
hi @vusisindane  

Calling from localhost is just fine.
Please check below latest Code 
https://github.com/agilecrm/php-api/blob/master/CurlLib/curlwrap_v2.php

In post man you will get the contact ( search contact )by mail id 

select Basic Auth give user name and Password

https://{domain}.agilecrm.com/dev/api/contacts/search/email/{email}

Request type : GET

please select below HEADERS
Content-Type : application/json,
Accept	: application/json,

Hope This will Help You, Please contact Agile CRM if you need any further help.

Thanks,
Agile CRM Support Team.
