### ISSUE TITLE
Documentation is unclear

### ISSUE THREAD

**Issue by DavidAPowers** [agilecrm/php-api#7]
Please update the documentation to be more clear. 

In curlwrap_v2.php, I set "AGILE_DOMAIN" to the full domain name:
**mydomain.agilecrm.com**

That doesn't work, it needs just the **subdomain** to run properly, but this isn't explicitly stated anywhere:
**mydomain**

**Comment by graut** [comment]
Hi @DavidAPowers ,

Thanks to point out domain related information. We have update new image describing domain, rest api key and email.

https://github.com/agilecrm/php-api#intro

Please contact - Agile CRM support team if have any question. 
Thanks
