### ISSUE TITLE
Listing all contacts

### ISSUE THREAD

**Issue by gfnasc** [agilecrm/php-api#9]
Hello,
Its possible list all registered contacts?

Tks;

**Comment by graut** [comment]
Hi @gfnascrentcars 

Yes this is possible using paging technique.

PHP call should be like this.

curl_wrap("contacts?page_size=5&cursor&global_sort_key=-created_time", null, "GET", "application/json");

Please check below video link of how to use paging technique to fetch list of contacts from Agile CRM

https://www.youtube.com/watch?v=jJAAZKqybQ4

Thanks

**Comment by rammohan-agile** [comment]
hi @gfnasc 
You can hit below URL in post man, you will get contacts,
select Basic Auth then give username and Password 
Method : POST

https://rammohanp.agilecrm.com/dev/api/contacts/list

Hope This Help You,i am closing the Issue , Please contact Agile CRM if need any further help.
Thanks

**Comment by darrenklein** [comment]
The `.../dev/api/contacts/list` route seems to have been deprecated.

**Comment by rammohan-agile** [comment]
Hi @darrenklein ,
      Thanks for using Agile CRM. I have checked above URL in POSTMAN and it's working fine,please refer the screen shot .Please try at your end once again and let us know if any issues.

![contact list](https://user-images.githubusercontent.com/47098529/62443645-0ab3eb80-b779-11e9-8726-98fd99aca875.png)

Thanks,
Agile Crm Support Team.

**Comment by darrenklein** [comment]
@rammohan-agile ah, thanks for looking into this, my mistake (it would seem) - but is there a reason that this method isn't listed in Agile's REST API docs?  I see a similar method for companies, but not for contacts - https://github.com/agilecrm/rest-api

**Comment by darrenklein** [comment]
Also, it was my mistake - I was making a GET request, rather than a POST, as you noted in your comments above.  It'd be very helpful to include this method in the docs.  Thanks so much for your hard work!

**Comment by darrenklein** [comment]
@rammohan-agile  It seems that the `.../list` method only returns 50 contacts, which is the default that would be returned by a GET request to `.../dev/api/contacts` - however, that method allows a `page_size` query param which can be used to return a larger number.

I'm in a bit of a pickle - I have more than 5000 contacts in my Agile space, and I need to import them all via the REST API.  Using the GET method, I can't seem to retrieve more than about 2500 records before the request takes too long (seems to cap at 60 seconds) and I get a 500 error:

```
The server encountered an error and could not complete your request. Please try again in 30 seconds.
```

Is there a way that I can reliably import the entire list of contacts when that list is fairly large?
